name: Testing
on:
  pull_request:
    - master
jobs:
  test:
    name: Testing iOS app
    runs-on: macOS-latest
    steps:
    - name: Repository checkout
      uses: actions/checkout@v2
    - name: Lint
      run: SwiftLint
    - name: Build for iOS
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild build-for-testing -scheme Block -destination "platform=iOS Simulator,OS=latest,name=iPhone 12" | xcpretty
    - name: Run iOS tests
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild test-without-building -scheme BlockTests -destination "platform=iOS Simulator,OS=latest,name=iPhone 12" | xcpretty
